[build]
  base = "/"  # This is the root directory of your project
  command = "pip install -r requirements.txt && gunicorn app:app"  # Install dependencies and run with gunicorn
  publish = "/"  # Publish the root directory, assuming your app is in the root

[functions]
  directory = "netlify/functions"  # Optional: if you have serverless functions, place them here (if used)

[build.environment]
  FLASK_APP = "app.py"  # Your main Flask app entry file (adjust if different)
  FLASK_ENV = "production"  # Set the Flask environment to production
