services:
  - type: web
    name: TextSummarizer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    region: oregon  # You can change this to another region if needed
    envVars:
      - key: FLASK_ENV
        value: production
