services:
  - type: web
    name: flask-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: FLASK_APP
        value: "app.py"  # Adjust if your app's main file has a different name
      - key: FLASK_ENV
        value: "production"  # Set to 'development' if you're testing locally
    plan: free  # You can change this to a different plan (e.g., "starter", "pro") based on your needs
    region: oregon  # Specify the region (e.g., "oregon", "frankfurt", etc.)
