name = "your-project-name"
type = "javascript"  # or "webpack" if you are using a bundler

[build]
  command = "npm run build"  # or "yarn build", depending on your setup
  cwd = "."  # current working directory, usually the root
  output_dir = "public"  # directory containing the built static files (adjust based on your app)

[build.upload]
  format = "modules"  # "modules" or "service-worker" depending on your app

[pages]
  pages_build_output_dir = "public"  # the output directory of the build command, adjust based on your setup
