name = "your-worker-name"
type = "python"

[build]
  command = "pip install -r requirements.txt"  # or any other necessary command to install dependencies
  output_dir = "dist"

[workers_dev]
  ip = "127.0.0.1"  # local dev IP (if needed)

[build.upload]
  format = "service-worker"  # when deploying a Python function in Workers
